### PR TITLE
Modified logging to log timestamps as well

### PR DESCRIPTION
**Pull request by pepedocs**
Hi, 

I'd like to see timestamps in will's logs for debugging purposes. Here's my initial PR.

Sample Output:

Thu, 05 May 2016 17:15:03 [DEBUG] message

Cheers

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
I like this.

Could we make it an option in the `config.py` ?

**Comment by pepedocs** [comment]
Thanks @brandonsturgeon .  Could you describe how it would look in the config.py or what part of the logging format will be configurable?

**Comment by brandonsturgeon** [comment]
Sure thing, @pepedocs 

I suppose that's up to you, but here're my suggestions:

1. In the config.py you'd have 2 vars, something like `logging_format=` and `logging_datefmt` which you could customize however you'd like

2. In the config.py you'd have `logging_uses_timestamps=True/False`


Either of those sound like a good idea to you?

**Comment by pepedocs** [comment]
Hi @skoczen, can you please have a look at my PR? It would be very helpful to see timestamps in will's logs.

**Comment by skoczen** [comment]
@pepedocs @brandonsturgeon this feels like a win to me, even if it changes the default behavior - folks can still override their logging as needed.

@pepedocs , thanks for making will even better! :)

-Steven

**Pull request merged**
