### PR TITLE
Feature/docker updates

### PR DESCRIPTION
**Pull request by mike-love**
- Move will to a decoupled container structure to allow more extensible for users/devs
- Create python specific versions 
- Create a latest generic file
- Update documentation

### CODE REVIEW

**Comment by skoczen** [comment]
@mike-love I can't tell you how happy this PR makes me.  Let me know when it's ready for review/merge!

**Comment by mike-love** [comment]
Feature wise, these builds are completing and the containers are running.  The dockerfile is pulling from the heywill/will repository.  

The only thing missing is documentation on self builds, for folks who want to roll their own containers (the cmds for docker build need some detail).  I should be able to get that done in the next few days-ish; however, if we don't think that's a high prio we can always add it to the 2.1.

**Comment by skoczen** [comment]
Fantastic - I'll merge this in when I'm back in work mode next week, then.   Whenever the docs are ready, I can just push them up without a re-release, so all good.

Thanks much for all your work in getting this working!

**Comment by mike-love** [comment]
@skoczen think we're good here with docs, and i cleaned some redundant stuff up

**Comment by skoczen** [comment]
@mike-love Merging this in now - feel free to send any doc updates as you've got 'em.  Thanks much for all your work on this!!

**Pull request merged**
