### PR TITLE
Add function to get user from roster by their nick

### PR DESCRIPTION
**Pull request by sivy**
Useful for plugins that expect a user mention in hear() or
respond_to()

### CODE REVIEW

**Comment by skoczen** [comment]
+1 by me, looks ready to go here.  Good by you? @sivy ?
Also, feel free to adjust your attribution in AUTHORS in this PR if it's not how you want it.

Will ship this and your other PR as 0.6.7 once I get a green light from you on this one!

**Comment by sivy** [comment]
:+1:

**Comment by sivy** [comment]
oh bother i was going to fix the authors file. Will do a new change on master.

**Comment by skoczen** [comment]
Don't sweat it- just post here, and I'll edit it in. :)

**Comment by skoczen** [comment]
FYI, I made a slight change on the settings parsing, in the explicit > implicit vibe. Just felt better.

```python
if "ALLOW_INSECURE_HIPCHAT_SERVER" in settings and\
    (settings["ALLOW_INSECURE_HIPCHAT_SERVER"] == True or settings["ALLOW_INSECURE_HIPCHAT_SERVER"].lower() == "true"):
```

Objections welcome.

**Comment by skoczen** [comment]
Released as [0.6.7](http://skoczen.github.io/will/improve/#releases) - thanks for the quick fix!

**Pull request merged**
