### PR TITLE
Change worldweatheronline API v1 => v2

### PR DESCRIPTION
**Pull request by woohgit**
The v1 does not support free keys anymore, but v2 does. Use the v2 API
instead of v1.

### CODE REVIEW

**Comment by skoczen** [comment]
+1 to this, will want to provide some docs for people upgrading, so not merging real quick right now, but this will get in!

If you don't mind, please add yourself as you'd prefer to be credited in the AUTHORS file, and push that onto this PR. Thanks!

**Comment by woohgit** [comment]
Thanks,

I added myself to the list :)

Waiting for the new release. ;]

**Comment by skoczen** [comment]
Merging this into the 0.6.6 release!   One change - I'm going to change the setting to `WORLD_WEATHER_ONLINE_V2_KEY`, and support both, since v1 keys still work. That way, anyone using v1 doesn't have things suddenly break!

**Comment by skoczen** [comment]
This is out as [0.6.6](http://skoczen.github.io/will/improve/#releases) - thanks for your patience and for making will better!

**Pull request merged**
