### PR TITLE
Add ability to send 1-to-1 notify messages

### PR DESCRIPTION
**Pull request by AlainMaesNokia**

### CODE REVIEW

**Comment by skoczen** [comment]
(Quick paste-on-all-open-issues update:)

**TL;DR**: New Will release EOM. Also, you're awesome.

**Full Update:** This may be TMI for you, and if so, cool, the thing you probably care about is above.  But given the total radio silence on my part - and the fact that I've always tried to create a community here where we got to be actual people instead of avatars and PRs, I wanted to give a bit more context.

As you may be aware from an earlier AFK, I got married in December, which was great, but burned the month from a Will perspective.  I planned to get back on it at the start of January, but instead found myself selling our house, and simultaneously hit with a surprisingly severe bout of depression.  The time since Jan 1 has been sort of a blur.  A dark blur, but a blur more than anything.   I saw the PRs and comments coming in, but didn't have the energy or time to do anything about them.

Things seem to be clearing up on both counts now, and I'm _really_ looking forward to getting these fixes in, catching up on bug reports, and being active in improving Will again. :)

With that, I'm aiming to get all outstanding PRs bundled into a release, and all issues replied to by the end of February.

Most of all, thanks for your contribution to Will, your patience with an imperfect, quite human project maintainer, and for continuing to come back, engage, and spend some of the precious seconds you get on earth making this project better.

I appreciate you.  Thank you.

**Comment by skoczen** [comment]
Hey @AlainMaesNokia , thanks much for submitting this - it seems that you're adding a new `notify()` method, but I don't see any documentation or context on what it is, or why it's a new method (instead of say a `notify=True` flag.)

Can you provide a little more context on this one?  Many thanks!

**Comment by AlainMaesNokia** [comment]
This method allows to send a unicast message to a specific user as opposed to sending to a chat room. As I did not really find a way to do that with the APIs that were available I added this one.

**Comment by skoczen** [comment]
Thanks, @AlainMaesNokia  - so to make sure I understand, the use-case is Will initiating a 1-1 message to a specific user?

If that's the case, I'd probably rather add (and document) the ability to add a `user=` or `handle=` kwarg to `say()`.   At present, on certain backends, I'm reasonably certain that just passing in `channel='skoczen'` would route it into a 1-1 anyhow.  But certainly that should work across backends.

What are your thoughts?

**Pull request closed without merging**
