### PR TITLE
[FEATURE] Remind <somebody> to ___ at ___

### PR DESCRIPTION
**Pull request by woohgit**
We are a pretty widely distributed company. My team-mates are working in US, Australia and New Zealand. I'm working from Hungary. Sometimes it's very useful to leave "reminders" for others in the Ops channel since we're working in a totally different time zone and e-mails are not always the best for timed reminders.

Currently only the "remind me to at" feature is available, so I managed to implement and refactor the RemindMePlugin and add the "remind somebody to at".

- The `remind_me_at` function is unchanged
- The `remind_me.py` has been renamed to `remind.py` to be more consistent.
- The `RemindMePlugin` class has been renamed to `RemindPlugin`
- The `remind_somebody_at` function has been added

### CODE REVIEW

**Comment by skoczen** [comment]
I can't tell you how happy this PR makes me.  Will get it reviewed and in in my next open-source sprint cycle!

Thanks for this and all your work on will!

**Comment by woohgit** [comment]
I think I should modify the "Bundled Plugins" documentation as well and add this new feature to reduce your work :) I'm adding it soon.

**Comment by skoczen** [comment]
+1 to docs, they're always appreciated. :)  Thanks much!

**Comment by woohgit** [comment]
Ok, docs have been updated as well, added a new section as "Remind somebody" just below the "Remind me" section. I also added a screenshot as well. :)

**Comment by skoczen** [comment]
Aw, man I love this.  Thanks so much.

This will go out in the next release!

**Comment by skoczen** [comment]
This is released (with a bunch of other stuff) as v[0.8](http://skoczen.github.io/will/improve/#releases)!

**Pull request merged**
