### PR TITLE
Add --backends option to generate_will_project

### PR DESCRIPTION
**Pull request by wontonst**
Help:

```
/argh/argh # generate_will_project --help
usage: generate_will_project [-h] [--config-dist-only]
                             [--backends {Slack,HipChat,Rocket.chat,Shell} [{Slack,HipChat,Rocket.chat,Shell} ...]]

optional arguments:
  -h, --help            show this help message and exit
  --config-dist-only    Only output a config.py.dist.
  --backends {Slack,HipChat,Rocket.chat,Shell} [{Slack,HipChat,Rocket.chat,Shell} ...]
                        Choose service backends to support.
```

Standard Use:
```
/argh/argh # generate_will_project --backends HipChat Shell

      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!

Welcome to the will project generator.


Generating will scaffold...
  /plugins
     __init__.py
     morning.py
  /templates
     blank.html
  .gitignore
  run_will.py
  config.py.dist
/usr/local/lib/python3.6/site-packages/will/scripts/../requirements/hipchat.txt
/usr/local/lib/python3.6/site-packages/will/scripts/../requirements/shell.txt
  requirements.txt
  Procfile
  README.md

Done.

 Your will is now ready to go. Run ./run_will.py to get started!
```

Bad choice:
```
/argh/argh # generate_will_project --backends Stride
usage: generate_will_project [-h] [--config-dist-only]
                             [--backends {Slack,HipChat,Rocket.chat,Shell} [{Slack,HipChat,Rocket.chat,Shell} ...]]
generate_will_project: error: argument --backends: invalid choice: 'Stride' (choose from 'Slack', 'HipChat', 'Rocket.chat', 'Shell')
```

Command line input behavior:

```
/argh/argh/argh # generate_will_project

      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!

Welcome to the will project generator.


Generating will scaffold...
  /plugins
     __init__.py
     morning.py
  /templates
     blank.html
  .gitignore
  run_will.py
  config.py.dist

Will supports a few different service backends.  Let's set up the ones you want:

  Do you want to enable Slack support? [y/n] n
  Do you want to enable HipChat support? [y/n] y
/usr/local/lib/python3.6/site-packages/will/scripts/../requirements/hipchat.txt
  Do you want to enable Rocket.Chat support? [y/n] nn
Please enter 'y' or 'n'.
  Do you want to enable Rocket.Chat support? [y/n] n
  Do you want to enable Shell support? [y/n] n
  requirements.txt
  Procfile
  README.md

Done.

 Your will is now ready to go. Run ./run_will.py to get started!
```

### CODE REVIEW

**Comment by wontonst** [comment]
I just went ahead and updated the Dockerfile and docs as well. I think we can do some thinking and decide if we want to always bundle all backends or not since right now it's a bit funky how the img is built, ie the user would have to use the Dockerfile to build the img rather than being able to pull from the docker registry and configure using `-e BACKENDS "Shell HipChat"`

**Comment by skoczen** [comment]
@wontonst love it.  Thanks for continuing to improve Will!

I'll pull this in to the next release!

As far as Docker, it's a good question - my gut given the above would be to just build it with support for all backends.   Then users can enable/disable in `config.py`.  Thoughts?

**Comment by skoczen** [comment]
This has been released in [2.1.3](http://skoczen.github.io/will/releases/#releases) - thanks for continuing to improve Will, @wontonst !

**Comment by wontonst** [comment]
👍

**Pull request merged**
