### PR TITLE
added a HipChat service status monitor

### PR DESCRIPTION
**Pull request by netjunki**
While HipChat was having a partial outage today I created a monitor for it based on the GitHub one.

### CODE REVIEW

**Comment by dpoirier** [comment]
Am I missing something?  If HipChat is down, won't we have trouble getting a message via HipChat from Will?

**Comment by netjunki** [comment]
The service was having a partial outage... so at least it could notify about that. :-)

**Comment by dpoirier** [comment]
Ah, I see.  It might be amusing to see my co-workers' reactions if Will tells them on Hipchat that Hipchat is having problems :-)

**Comment by skoczen** [comment]
Nice, I dig it. @netjunki thanks for the contribution.  I'll get this bundled into the next major release.

**Comment by skoczen** [comment]
This is released (with a bunch of other stuff) as v[0.8](http://skoczen.github.io/will/improve/#releases)!

**Pull request merged**
