### PR TITLE
Added urban dictionary definition plugin

### PR DESCRIPTION
**Pull request by Ironykins**
This is a plugin I wrote for my team. It allows us to find the definitions of words using the most reputable dictionary online: Urban Dictionary.

### CODE REVIEW

**Comment by skoczen** [comment]
Hey @Ironykins , I'm a +1 to this idea, but think having the verb just be "define" is going to go badly for a lot of teams, especially given the content of urban dictionary.   Opposition to it being 

`@will urban dictionary foo`, or something similar?

**Comment by skoczen** [comment]
Also, thanks for submitting a PR, and for your patience with my response time!

**Comment by Ironykins** [comment]
Haha, you're right. We've already hit some pretty offensive stuff. The command has been changed to 'urban dictionary'. And thanks for taking the time to consider adding this!

**Comment by skoczen** [comment]
Hey, just tossing out a quick note on this and all the other PRs to say thanks for your patience.  

Neither will nor your contributions have been forgotten!

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible.  Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.)  Thanks for hanging in there!

**Comment by skoczen** [comment]
This is released in [0.9.3](http://skoczen.github.io/will/improve/#releases) - thank you so much for your patience, and even more so for your contributions that made will even better!

-Steven

**Comment by Ironykins** [comment]
Thanks man! I'm glad you could find time to keep working on your open source stuff. I know work can sometimes be all-consuming. Keep it up!

**Comment by skoczen** [comment]
Thanks, @Ironykins !

**Pull request merged**
