### PR TITLE
feature/access_control_list ACL implementation for issue #109

### PR DESCRIPTION
**Pull request by woohgit**
This is a basic implementation. I kept the admin_only feature for compatibility reasons as well. Perhaps we could remove it later on. Need to discuss it.

- Added tests for the admin_only case, to make sure i'm not breaking anything
- Added tests for the ACL related functions, to make sure I'm doing the right thing
- Added documentation and updated old ones
- pep8 fixes at some files, but we still have a lot of unused imports

### CODE REVIEW

**Comment by skoczen** [comment]
I really dig this, but want to fully wrap my head around it, and that's not happening in my mad dash to get a dozen PRs in and out this afternoon.  Planning on merging this in though - thanks for your patience!

**Comment by woohgit** [comment]
Sure, no rush at all. We're using it for more than 1+ month and seems to be very cool. :)

**Comment by skoczen** [comment]
Looks great - will be moving the docs around a bit, but this is fantastic!  Thanks for all your work on it, and your patience!

This will go out this afternoon.

**Comment by skoczen** [comment]
@woohgit ,
Hey, so as I'm playing with this, I think it'd be a bit cleaner if the `config.py` were like this:

```python

ACLS = {
   "ops":  ["joe", "sally"],
   "admin": ["trisha"],
}
```

Since you're the only ones using this right now, now is the easiest time to make the change.  I'm happy to do the tweaks over here.  However - is there anything I'm missing that made you choose the other approach?

**Comment by skoczen** [comment]
Created https://github.com/skoczen/will/pull/151 with the changes.  If you've got time in the next few hours to give feedback, awesome.  

If not, I've tested this out a bunch, and I think the only changes you'll need to make is a quick refactor of your config.py - saving a few lines of code anyhow.  So, I'll push this out in this release, and if there's a big problem, we can address it with a quickfix.

Thanks!

-Steven

**Comment by skoczen** [comment]
This is now released as [v0.9](http://skoczen.github.io/will/improve/#09-may-29-2015)!  Let me know if you do spot anything!

**Comment by woohgit** [comment]
:+1:

**Pull request merged**
