### PR TITLE
Cleaned up some of the regex used by default plugins

### PR DESCRIPTION
**Pull request by shadow7412**
This is mostly to avoid some of the false positives I've experienced, causing will to pipe in with comments that make no sense (for example, nightly build failed last night caused a response of 'have a good night!')

While some of these are disputable for comedic value (and I of course welcome such disputes) I think they'll make will seem a bit smarter.

Also I added in to the reminder regex - saying `remind me to do thing AT 15 minutes` makes me a little sad :P

### CODE REVIEW

**Comment by skoczen** [comment]
Hey @shadow7412 ,

Broadly, I'm a +1 on these - will take a closer look and get it merged in on my next sprint!

Thanks for continuing to improve will!

-Steven

**Comment by shadow7412** [comment]
I didn't realise pull requests auto update... Therefore I've accidentally snuck in that if a plugin raises SystemExit, it will bubble instead of getting caught by the catchall.

This is because I wanted my deployed will bot to be able to self update.

**Comment by skoczen** [comment]
Hey,

No worries, but yeah, go ahead and split those up.

You can just make a commit that undoes the changes, push it, and it'll all be good.

As for your other changes, I'm a -1 to plugins quitting will (at least at first blush), and your pong function is named ping - it gets rid of the original! :)

**Comment by shadow7412** [comment]
*shakes head* ping has been renamed to pong... obviously did that too early in the morning.
I've pulled out SystemExit for now - I shall make my case in another ticket another time.

**Comment by skoczen** [comment]
Just a quick note on this that I still plan to get it into the next release - have been slammed with an app launch, and no spare cycles for will.  But it will be coming!

**Comment by skoczen** [comment]
Hey, just tossing out a quick note on this and all the other PRs to say thanks for your patience.  

Neither will nor your contributions have been forgotten!

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible.  Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.)  Thanks for hanging in there!

**Comment by shadow7412** [comment]
:+1:

**Comment by skoczen** [comment]
This is released in [0.9.3](http://skoczen.github.io/will/improve/#releases) - thank you so much for your patience, and even more so for your contributions that made will even better!

-Steven

**Pull request merged**
