### PR TITLE
Fixed "nodename nor servname provided, or not known"

### PR DESCRIPTION
**Pull request by bykof**

### CODE REVIEW

**Comment by skoczen** [comment]
Goodness I love fixes like this :)   Thanks, @bykof !

Would you mind adding yourself in the `README` with the attribution you'd prefer?

**Comment by bykof** [comment]
@skoczen No thanks, i think to fix a link is not really a contribution :D 
I will adding myself in the `AUTHORS` if I will provide a "real" fix but thank you for the invitation

**Comment by skoczen** [comment]
@bykof I appreciate your humility, but I'll be adding you either way - you've contributed code to Will.  Mostly, I'd like to have you listed in the way that's best for you!   

No worries if it's too much trouble. Otherwise, I'll just list you as

`bykof, https://github.com/bykof`

Cheers!

**Comment by bykof** [comment]
@skoczen damn son, so much politeness 👍 
Thank you for listing me but now it's more important for me to merge this pull req :D 

Cheers my friend, I hope we will meet some day for a beer.

**Comment by skoczen** [comment]
Both politeness and a strategic long-term interest in a strong community.  Will has been contributed to by a lot of people, and it's important both for them, and for Will's long-term interest that people feel like their contributions are honored, and have a stake in the outcome.  :)

I've added you as just "bykof" - feel free to toss a PR over anytime you want your actual name.  

This will be merged in and released with 1.0

**Pull request merged**
