### PR TITLE
Don't get stuck if > 2000 rooms

### PR DESCRIPTION
**Pull request by woparry**
Update the start index correctly so that we actually get all the way through the list.

### CODE REVIEW

**Comment by woparry** [comment]
Fixes https://github.com/skoczen/will/issues/234

**Comment by skoczen** [comment]
This looks great - I'm in the midst of a move to Japan, but my sincere hope is to caught up on this (and all the other) PRs once I'm settled in there.

Thank you so much for contributing to will!

**Comment by skoczen** [comment]
@woparry thanks for this PR, and your extended patience! I'm merging this into the next release now!

@woohgit both moved to Japan, and moved away, in the time it took me to respond. :)  Are you still there?  Where at?

**Comment by woohgit** [comment]
@skoczen Tokyo. I plan to stay here now. :) Are you still in New Zealand?

**Comment by skoczen** [comment]
Yep, still in NZ - and planning to have this be my home base for the forseeable future (met someone here, fell in love, the whole gig.)  Staying in Tokyo sounds awesome!  Have you been down South at all?  I adored Kyoto - really different, but amazing.

**Pull request merged**
