### PR TITLE
Feature/travis dockerbuild

### PR DESCRIPTION
**Pull request by mike-love**
Opening to enable auto builds of containers using travis; some things need to be hammered out:

- [x] Build only specific branch patterns?

- [x] Push to docker hub should only be on master
- [ ] Credentials need to be stored somewhere to do a push

### CODE REVIEW

**Comment by skoczen** [comment]
Some quick thoughts on the above questions:

#### Build only specific branch patterns?

+1, we (I) just need to standardize the branch structure.  Would vote for builds of `master`, `beta`, and `alpha`. 

#### Push to docker hub should only be on master

+1 . Also, I need to be consistent that master is only committed/merged to via a reviewed PR.

####  Credentials need to be stored somewhere to do a push

I believe Travis allows secure storage in env.  If not, CircleCI definitely does, and I've been using them for similar CI/CD structures

**Comment by mike-love** [comment]
reopening this after a major screwup on my fork

**Comment by mike-love** [comment]
@skoczen 
1. Branch patterns are easy enough (i think), if you settle on a pattern we can add that.  Right now, master is the only branch that'll trigger a latest tag and a push. 
2. The functionality to push is in the .travis.yml; we need to store credentials and that should be good. Which leads to....
3. We can store as encrypted environment vars.  Just need to figure out the best way to do this on the i'll get some details and work through this.

**Comment by skoczen** [comment]
@mike-love thinking about getting 2.1 out this week - what can I do to help on this?

**Comment by skoczen** [comment]
Just a quick update that I've added willorg as a user, and will be encrypting credentials into the travis file for push1

**Comment by skoczen** [comment]
Just a quick note - I'm going to merge this and the encrypted creds branch into master, and see how it all comes together - we can then move forward from that base!

**Pull request merged**
