### PR TITLE
[PagerDuty] Ability to ack/resolve/reassign and set maintenance

### PR DESCRIPTION
**Pull request by woohgit**
A basic plugin for handling PagerDuty incidents.

- **@will pd ack**: Acknowledge all open incidents assigned to you
- **@will pd ack!**: Acknowledge all open incidents
- **@will pd ack [incident number 1] [incident number 2]**: Acknowledge one or more specific incidents
- **@will pd resolve**: Resolve all acknowledged incidents assigned to you
- **@will pd resolve!**: Resolve all acknowledged incidents
- **@will pd resolve [incident number 1] [incident number 2]**: Resolve one or more specific incidents
- **@will pd reassign [incident number 1] [somebody]**: Reassign the incidents to somebody
- **@will pd maintenance [service name] [hour(s)]h**: Schedule a new maintenance window for x hours

In case if the HipChat e-mail address and the PagerDuty e-mail address are the same, `@will` can associate the two.

In the future, I'll add an additional feature where a HipChat user can define his own PagerDuty e-mail address, so in case if the HipChat user set his own PD e-mail, the associate function will use that e-mail address instead of the `message.sender['hipchat_id'])['email']`.

But generally I think those two are the same, so we're good to go with this and iterate later.

### CODE REVIEW

**Comment by skoczen** [comment]
This is brilliant.  I love it.  I've wanted something similar for our devops, and haven't had the time to code it up.  Will merge this in on my next sprint!

**Comment by woohgit** [comment]
I'll add a few more commits to this. I found a few "bugs" wrt handling maintenance (I only support a-zA-Z[space] but not spec chars like underline and dash. It's fixed in our envronment, but had no time to move those changes here :) But I think I have a few more days until your next sprint ;)

**Comment by skoczen** [comment]
Yep, you've got at least a week, I'd guess. :)

**Comment by skoczen** [comment]
This is now released as [v0.9](http://skoczen.github.io/will/improve/#09-may-29-2015), and I am so stoked about it. :)

**Pull request merged**
