### PR TITLE
Deal gracefully with zombie users

### PR DESCRIPTION
**Pull request by BrianGallew**
Will will occasionally come across resources owned by users who have
been deleted.  The roster code doesn't handle that well.

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
Just out of curiosity, what is the result of will coming across resources belonging to deleted users?

**Comment by BrianGallew** [comment]
The result is an uncaught exception.  

```
self.full_hipchat_user_list[hipchat_id]
```
That value is used in the assignment, but there's no guarantee that the hipchat_id actually maps to a a value in self.full_hipchat_user_list.  And when it doesn't, the lookup results in a KeyError.  And with no exception handling, the entire listener loop dies, leaving Will running but unresponsive.

**Comment by brandonsturgeon** [comment]
Iiinteresting, hearing this explains some of the stranger instances of a non responsive Will in the past. 

Good job!

**Comment by skoczen** [comment]
Nice work, @BrianGallew - thanks so much for the improvements!

This will be merged into the next release, out in the next couple days!

**Pull request merged**
