### PR TITLE
Create pug.py

### PR DESCRIPTION
**Pull request by camilonova**

### CODE REVIEW

**Comment by skoczen** [comment]
Love it.  Pulling it into the next release.

**Comment by shadow7412** [comment]
Can we change the regex of this to be `"\bpug\b"`? That way words that happen to have the string 'pug' in them won't cause random dogs... :P

**Comment by skoczen** [comment]
I can indeed make that adjustment. Also, merging this in!

**Comment by skoczen** [comment]
This is now released as [v0.9](http://skoczen.github.io/will/improve/#09-may-29-2015)!  Thanks again!

**Pull request merged**
