### PR TITLE
spellfix: reccomended -> recommended

### PR DESCRIPTION
**Pull request by jquast**

### CODE REVIEW

**Comment by skoczen** [comment]
Love PRs like this - will get this merged in on my next open-source cycle!

If you'd be willing, can you toss your name and the attribution you'd like in the AUTHORs file?

Thanks for making will better!

**Comment by jquast** [comment]
not this time, maybe next, no biggie.

would you be interested in sqlitedict (sqlite) backend opposed to redis?

**Comment by skoczen** [comment]
Cool, I have a good habit on this project I like to keep up of crediting contributions on everything, even stuff like typos - it all adds up in a real way.  I'll just go with the default, and you can change on your next PR if you'd like!

Sqlitedict - possibly, as an option.  I'm not super familiar with it - how well does it handle concurrency?

**Comment by jquast** [comment]
> Support for access from multiple threads to the same connection (needed by e.g. Pyro). Vanilla sqlite3 gives you ProgrammingError: SQLite objects created in a thread can only be used in that same thread.

> Concurrent requests are still serialized internally, so this “multithreaded support” doesn’t give you any performance benefits. It is a work-around for sqlite limitations in Python.

**Comment by skoczen** [comment]
Cool, in theory that should work then.  

Ideally, I'd love to see this implemented using the backend/engine pattern, where redis is the default, and sqlitedict is an option.

Is that something you'd be interested in digging into?  Or, can you provide additional context on the motivation for using sqlitedict?

**Comment by skoczen** [comment]
Merging this fix in - if you're digging sqlite, please open as a new issue!

**Comment by skoczen** [comment]
The spellfix is released (with a bunch of other stuff) as v[0.8](http://skoczen.github.io/will/improve/#releases)!

**Comment by jquast** [comment]
Sure. I ended up contributing to sqlitedict and became a contributor, so I'm wrapping up a new release there first.

To answer your question about why sqlitedict as a motivation: it lowers the cost of setting up a "will" for the first time, its hard enough figuring out all the xmpp/account configs. I would hope it would make a first-time setup a lot easier, some people may "just want a hipchat bot", maybe not even know python well, and now they are also installing redis for the first time.

(btw I love redis and use it often, i have nothing against it)

**Pull request merged**
