### PR TITLE
Display timezone when asking what time is it

### PR DESCRIPTION
**Pull request by woohgit**
I think it's an useful small feature, especially when you want to remind will to do something at a specific time, but you and will are in a completely different TZ.

### CODE REVIEW

**Comment by skoczen** [comment]
Love it.  Doubly so because I'm never on the same TZ as the rest of my team.   Will get this merged in on my next will sprint.  Thanks for your continued contributions!

**Comment by woohgit** [comment]
Yeah, same here. I'm from Hungary (CET), my team is from New Zealand, Australia and additional few from Austin, Seattle, New York. Sometimes we're disagreed even on the day :D

**Comment by skoczen** [comment]
Hah, hear you there - spent the fall/winter in Thailand, with a US-based team. 

Goodness we get to live in a cool time.

**Comment by skoczen** [comment]
This is now released as [v0.9](http://skoczen.github.io/will/improve/#09-may-29-2015)!  Thanks again!

**Pull request merged**
