### PR TITLE
Batch getting rooms

### LINKED ISSUE #166: Do not fetch room list
Hi,

When there's a ton of rooms, Will requires using the V1 token.

Would it be possible for Will to not try to fetch all available rooms, but instead just accept a list of Hipchat room id that it can directly connect to? From what I read of the code, `available_rooms` is mainly used to translate a room name to a room id.

### PR DESCRIPTION
**Pull request by charlax**
Fixes #166

### CODE REVIEW

**Comment by charlax** [comment]
This is a first stab, tell me what you think of this.

**Comment by charlax** [comment]
(I'm gonna look at tests and docs after)

**Comment by skoczen** [comment]
First glance, looks good.  I'm just coming off a crazy launch, and taking a few days unplugged to recharge.  I'll take a closer look after that! 

Thanks for taking this on! 

-Steven

**Comment by skoczen** [comment]
Hey, just tossing out a quick note on this and all the other PRs to say thanks for your patience.  

Neither will nor your contributions have been forgotten!

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible.  Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.)  Thanks for hanging in there!

**Comment by skoczen** [comment]
This is released in [0.9.3](http://skoczen.github.io/will/improve/#releases) - thank you so much for your patience, and even more so for your contributions that made will even better!

-Steven

**Pull request merged**
