### PR TITLE
Tox support for py3, flake8 cleanup

### PR DESCRIPTION
**Pull request by chillipeper**
- Add py35, py36, py37 envlist in tox.ini

- Fix flake8 errors
```
./will/utils.py:102:9:` E117 over-indented
./will/main.py:39:5: F821 undefined name 'reload'
./will/main.py:565:17: E117 over-indented
./will/backends/io_adapters/hipchat.py:288:25: E117 over-indented
```
- Bump version of PyYAML to 3.13 and requests to 2.20.0 to support py37.
- Make tests pass in travis

Result:

```
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
  py27: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  py37: commands succeeded
  flake8: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by chillipeper** [comment]
Added support for python3.4. This should resolve #366  issue and PR #367  should not be longer needed.

@wontonst could you please take a look when you have a chance?

**Comment by wontonst** [comment]
Looks good to me. Have you checked that the minor version upgrades to req.txt do not break anything?

**Comment by chillipeper** [comment]
I have been using those upgrades with python 3.7 in prod for the last month, nothing obvious has broken.

**Comment by rsalmond** [comment]
I've also been using an updated copy of requests in prod for a while without issues.

**Pull request merged**
