### PR TITLE
save "all_listener_regexes" to storage

### PR DESCRIPTION
**Pull request by acommasplice**
So "programmer help" works as expected.

### CODE REVIEW

**Comment by netjunki** [comment]
@skoczen I was seeing this as well with slack and this PR fixes the issue. Though the formatting of it is all mucked up. :-)

**Comment by skoczen** [comment]
(Quick paste-on-all-open-issues update:)

**TL;DR**: New Will release EOM. Also, you're awesome.

**Full Update:** This may be TMI for you, and if so, cool, the thing you probably care about is above.  But given the total radio silence on my part - and the fact that I've always tried to create a community here where we got to be actual people instead of avatars and PRs, I wanted to give a bit more context.

As you may be aware from an earlier AFK, I got married in December, which was great, but burned the month from a Will perspective.  I planned to get back on it at the start of January, but instead found myself selling our house, and simultaneously hit with a surprisingly severe bout of depression.  The time since Jan 1 has been sort of a blur.  A dark blur, but a blur more than anything.   I saw the PRs and comments coming in, but didn't have the energy or time to do anything about them.

Things seem to be clearing up on both counts now, and I'm _really_ looking forward to getting these fixes in, catching up on bug reports, and being active in improving Will again. :)

With that, I'm aiming to get all outstanding PRs bundled into a release, and all issues replied to by the end of February.

Most of all, thanks for your contribution to Will, your patience with an imperfect, quite human project maintainer, and for continuing to come back, engage, and spend some of the precious seconds you get on earth making this project better.

I appreciate you.  Thank you.

**Comment by skoczen** [comment]
@acommasplice thanks so much for this - would you mind adding the attribution you prefer to `AUTHORS`?  Will be pulling this into the next release shortly!

**Comment by skoczen** [comment]
Perfect, thanks @acommasplice !

**Comment by skoczen** [comment]
This has been released in 2.1.1 - thanks for making Will even better, @acommasplice !

**Pull request merged**
