### PR TITLE
Slack RTM reconnect

### PR DESCRIPTION
**Pull request by cmachine**
Catches errors when reading from the Slack RTM and makes up to 3 reconnection attempts after an increasing delay.

### CODE REVIEW

**Comment by mattcl** [comment]
Given the issue with the underlying library (https://github.com/slackapi/python-slackclient/issues/118), I don't think a finite number of reconnects is sufficient. It seems like the websocket error will just happen periodically, which is why I (biased) prefer #333 since it just reconnects forever for this specific exception. I considered a recursive call as well but since it's infinite, wanted to avoid risking overflows if the method was modified incorrectly in the future.

**Comment by cmachine** [comment]
That makes sense, I'll close this in favor of #333

**Comment by skoczen** [comment]
@cmachine thanks for this PR - will get a fix out in 2.1.1!

**Comment by skoczen** [comment]
This has been released in 2.1.1!

**Pull request closed without merging**
