### PR TITLE
Accept invitations to rooms

### PR DESCRIPTION
**Pull request by dpoirier**
Teach Will to accept invitations.

### CODE REVIEW

**Comment by skoczen** [comment]
Doing a review of open PRs - @dpoirier @mikn, does the new "join everything" functionality effectively solve your usecases?  Are there still outstanding needs in the vein of this PR?

**Comment by dpoirier** [comment]
Sorry, just now getting around to updating to a modern Will.  Is there a new functionality to have Will join new rooms when they're created?

**Comment by skoczen** [comment]
Nope - but there is (as of 0.5) a `config.py` with tons of options.  Notably, if `ROOMS` (and the env's `WILL_ROOMS`) is not set, will will join every room on startup.  He doesn't yet receive notices on creation.

For the upgrade, I'd say it might be worth just spinning up a blank virtualenv/folder and running `generate_will_project`, so you can see how it's laid out now.  The new, config-based version should be backwards-compatible with the old pure-env approach, but imo moving to a config.py makes config and maintenance much simpler.

As for joining when new rooms are created, from here, the implementation path seems reasonably clear:
1. Have will get alerts when new rooms are created.
2. Check that room against the list of rooms he knows to join (including all)
3. Join if appropriate.

Does that hit your needs?

**Comment by dpoirier** [comment]
That sounds like exactly what we'd want.

**Comment by skoczen** [comment]
Fantastic.  That is now officially the spec for this issue, then.

I would guess it'd be a few weeks until I've got the cycles to write that.  If you've got time before that, I'd of course happily accept a PR.

I'm not sure on XMPP broadcasting room creation, and it looks like (on a quick glance) the v2 hipchat API doesn't have a hook for room creation.  Slow-polling the list of rooms seems insane, but might work.  As always, better ideas are welcome.

**Comment by dpoirier** [comment]
Being addressed in other pull requests.

**Pull request closed without merging**
