### PR TITLE
Allow will.plugin.WillPlugin.say to accept a string room param + small cleanup

### PR DESCRIPTION
**Pull request by wontonst**
See #289 for context

### CODE REVIEW

**Comment by skoczen** [comment]
Fantastic!  Thanks so much for the contribution, @wontonst !   

This looks great.

Would you mind adding yourself to `AUTHORS` with the attribution you'd prefer as well?

**Comment by wontonst** [comment]
@skoczen added myself. Happy to help improve this project! 😄

**Comment by skoczen** [comment]
Fantastic, thanks!!

Will merge this in this week, once I have release schedule for 2.0b1 set!

**Comment by skoczen** [comment]
@wontonst this is out as [1.0.2](http://skoczen.github.io/will/improve/#releases) - thanks for your help!

**Pull request merged**
