### PR TITLE
Handle exceptions while getting JSON status

### PR DESCRIPTION
**Pull request by woohgit**
I saw a lot of exceptions during fetching the status JSON from github/heroku/hipchat on a weekly basis.

These exceptions should be handled, and a `pass` seems to be valid "handler" :)

### CODE REVIEW

**Comment by skoczen** [comment]
Interesting.  I see a rogue "heroku's back up" messages from time to time, but never an exception.  Any idea what the exception is?

**Comment by woohgit** [comment]
Sure, for me it seems hipchat/heroku/github has 0 entries in their JSON feed, or no JSON at all. See below an exception:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/cloudbees/will_venvs/current/local/lib/python2.7/site-packages/will/decorators.py", line 27, in wrapped_f
    f(*args, **kwargs)
  File "/opt/cloudbees/will_venvs/current/local/lib/python2.7/site-packages/will/plugins/devops/hipchat_is_up.py", line 13, in hipchat_is_up
    if r.json()["status"]["indicator"] != last_status:
  File "/opt/cloudbees/will_venvs/current/local/lib/python2.7/site-packages/requests/models.py", line 776, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by skoczen** [comment]
Awesome, thanks for the info.  Mind just catching the `ValueError`, instead of all exceptions?

Also, thanks for your patience.  Neither will nor your contributions have been forgotten. :)

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible.  Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.)  Thanks for hanging in there!

**Comment by skoczen** [comment]
This is released in [0.9.3](http://skoczen.github.io/will/improve/#releases) - thank you so much for your patience, and even more so for your contributions that made will even better!

-Steven

**Pull request merged**
