### PR TITLE
Added bitbucket_is_up plugin modeled after hipchat_is_up

### PR DESCRIPTION
**Pull request by mvanbaak**

### CODE REVIEW

**Comment by skoczen** [comment]
This looks great, thanks @mvanbaak ! 

Can you please add yourself to the `AUTHORS` file, with the credit you'd prefer?

I'll get this in on my next sprint - thanks for your patience!

-Steven

**Comment by skoczen** [comment]
Hey, just tossing out a quick note on this and all the other PRs to say thanks for your patience.  

Neither will nor your contributions have been forgotten!

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible.  Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.)  Thanks for hanging in there!

**Comment by mvanbaak** [comment]
:) Updated AUTHORS as you suggested. Thanks!

**Comment by skoczen** [comment]
Awesome, thanks!  Will get this in!

**Comment by skoczen** [comment]
This is released in [0.9.3](http://skoczen.github.io/will/improve/#releases) - thank you so much for your patience, and even more so for your contributions that made will even better!

-Steven

**Pull request merged**
