### PR TITLE
Refactor Storage to allow different backends

### PR DESCRIPTION
**Pull request by borgstrom**
I am unable to run Redis in my environment, but am able to run Couchbase and also use local disk storage.

I refactored the StorageMixin so that it's abstract and a new setting named STORAGE_BACKEND defines which backend actually handles the persisting of the values.

This doesn't introduce anything that's not backwards compatible and allows existing deployments of Will to run unchanged.

As part of this I refactored the requirements so that there could be a requirements file for couchbase as well as redis.

### CODE REVIEW

**Comment by skoczen** [comment]
@borgstrom, 

You rock.

This looks fantastic, and is exactly what I was hoping the storage backends would turn into someday. Thanks so much for the clear, and well-architected code!

I'll get this reviewed and merged in on my next will sprint.  Thanks for making will even better!

-Steven

**Comment by borgstrom** [comment]
Thanks, @skoczen!  Glad to contribute, I might be switching to HipChat in the near future and am glad there's such a nice framework out there for me to port my bots over :)

There's one `XXX TODO` note inside of StorageMixin about how to handle import errors (i.e. an invalid `STORAGE_BACKEND` was supplied).

Currently the `ImportError` just bubbles up.  I initially thought that this would be fine since inside of `bootstrap_storage_mixin` in main.py there's a try/except block, but it appears that due to multiprocessing and the verification of credentials one of the child processes calls `save()` before we reach `bootstrap_storage_mixin`.

```
#566 ❯❯❯ ./run_will.py 

      ___/-\___
  ___|_________|___
     |         |
     |--O---O--|
     |         |
     |         |
     |  \___/  |
     |_________|

      Will: Hi!


Verifying environment...
  ✓ WILL_USERNAME
  ✓ WILL_PASSWORD
  ✓ WILL_V2_TOKEN

Verifying credentials...
  ✓ Dev Bot authenticated
  ✓ @DevBot verified as handle

Loading configuration...
  Importing config.py... 
    ! Warning: STORAGE_BACKEND is set in the environment as 'file', but overridden in config.py as 'nope'.
  Verifying settings... 
    ! Warning: no ROOMS list found in the environment or config.  This is ok - Will will just join all available rooms.
    ! Warning: no PUBLIC_URL found in the environment or config.  Defaulting to 'http://localhost:9000'.
    ! Warning: no V1_TOKEN found in the environment or config.This is generally ok, but if you have more than 30 rooms, you may recieve rate-limit errors without one.
    ✓ ALLOW_INSECURE_HIPCHAT_SERVER
    ✓ ADMINS
    ✓ FILE_DIR
    ✓ HANDLE
    ✓ HTTPSERVER_PORT
    ✓ HIPCHAT_SERVER
    ✓ NAME
    ✓ PUBLIC_URL
    ✓ PLUGINS
    ✓ PLUGIN_BLACKLIST
    ✓ PASSWORD
    ✓ ROOMS
    ✓ REQUESTS_OPTIONS
    ✓ STORAGE_BACKEND
    ✓ TEMPLATE_DIRS_PICKLED
    ✓ USERNAME
    ✓ USE_PROXY
    ✓ V2_TOKEN

Verifying rooms...
Process Process-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/eborgstr/.virtualenvs/will/lib/python2.7/site-packages/will-0.8.2-py2.7.egg/will/mixins/room.py", line 77, in update_available_rooms
    self.save("hipchat_rooms", self._available_rooms)
  File "/Users/eborgstr/.virtualenvs/will/lib/python2.7/site-packages/will-0.8.2-py2.7.egg/will/mixins/storage.py", line 34, in save
    self.bootstrap_storage()
  File "/Users/eborgstr/.virtualenvs/will/lib/python2.7/site-packages/will-0.8.2-py2.7.egg/will/mixins/storage.py", line 27, in bootstrap_storage
    storage_module = importlib.import_module(module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named nope_storage
```

At that point will just hangs until you break.  Not his usual friendly self.

I see three options:

1. I can refactor main as part of this so that will verifies all settings before starting any other processes, but that may end up being a large-ish amount of changes that we don't want to include in this PR.
2. We can leave this as is and I can refactor main as a separate PR.
3. I can handle the `ImportError` directly in the mixin so that it's just more friendly when saving before the bootstrap happens in main.

Let me know your thoughts.

**Comment by skoczen** [comment]
Hey @borgstrom , thanks for your thoughts and completeness on this.  I'm mostly in favor of #3 - if an invalid backend is provided, will should fail on startup, loudly, with clear instructions.   I'm doing a ton of merges today, so will see if I can knock that out in the process!

**Comment by skoczen** [comment]
Tracking those changes over in #152.

**Comment by skoczen** [comment]
Alright, I think this is ready to go!  I've merged #152 in, and this will go out shortly.

Short version of the fix - I pulled the code out of `bootstrap_settings` that didn't belong there and was triggering the save problem, and moved it below the storage bootstraps.  Then, the error bubbled up properly, is now caught, and all's well!

Thanks once again for this PR - it's wonderfully done, well-documented, clear, and it works.  Your work is so, so appreciated.

-Steven

**Comment by skoczen** [comment]
This is now released as [v0.9](http://skoczen.github.io/will/improve/#09-may-29-2015)!  Thanks again!

**Pull request merged**
