### PR TITLE
pytest for acls

### PR DESCRIPTION
**Pull request by chillipeper**
Couple of changes here:

- add pytest and pytest-cov to requirements-dev.txt
- name change of **_test_acl_** function to **_verify_acl_** to avoid pytest conflicts
- change deprecated **_logging.warn_** for **_logging.warning_**
- parametrization of ACL tests
- add of conftest.py with message and person fixtures for acl tests use and future reuse

```
will/tests/test_acl.py::test_get_acl_members[ENGINEERING_OPS] PASSED                                                                                                                                 [  2%]
will/tests/test_acl.py::test_get_acl_members[engineering_devs] PASSED                                                                                                                                [  5%]
will/tests/test_acl.py::test_is_acl_allowed_returns_true[bob, {'ENGINEERING_OPS'}] PASSED                                                                                                            [  8%]
will/tests/test_acl.py::test_is_acl_allowed_returns_true[Alice, {'ENGINEERING_OPS'}] PASSED                                                                                                          [ 11%]
will/tests/test_acl.py::test_is_acl_allowed_returns_true[eve, {'engineering_devs'}] PASSED                                                                                                           [ 14%]
will/tests/test_acl.py::test_is_acl_allowed_returns_true[bob, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                        [ 17%]
will/tests/test_acl.py::test_is_acl_allowed_returns_true[Alice, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                      [ 20%]
will/tests/test_acl.py::test_is_acl_allowed_returns_true[eve, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                        [ 23%]
will/tests/test_acl.py::test_is_acl_allowed_returns_false[bob, {'engineering_devs'}] PASSED                                                                                                          [ 26%]
will/tests/test_acl.py::test_is_acl_allowed_returns_false[Alice, {'engineering_devs'}] PASSED                                                                                                        [ 29%]
will/tests/test_acl.py::test_is_acl_allowed_returns_false[eve, {'ENGINEERING_OPS'}] PASSED                                                                                                           [ 32%]
will/tests/test_acl.py::test_is_acl_allowed_returns_false[juan, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                      [ 35%]
will/tests/test_acl.py::test_is_acl_allowed_returns_false[pedro, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                     [ 38%]
will/tests/test_acl.py::test_verify_acl_is_disabled[bob, {'engineering_devs'}] PASSED                                                                                                                [ 41%]
will/tests/test_acl.py::test_verify_acl_is_disabled[Alice, {'engineering_devs'}] PASSED                                                                                                              [ 44%]
will/tests/test_acl.py::test_verify_acl_is_disabled[eve, {'ENGINEERING_OPS'}] PASSED                                                                                                                 [ 47%]
will/tests/test_acl.py::test_verify_acl_is_disabled[juan, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                            [ 50%]
will/tests/test_acl.py::test_verify_acl_is_disabled[pedro, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                           [ 52%]
will/tests/test_acl.py::test_verify_acl_is_allowed[bob, {'ENGINEERING_OPS'}] PASSED                                                                                                                  [ 55%]
will/tests/test_acl.py::test_verify_acl_is_allowed[Alice, {'ENGINEERING_OPS'}] PASSED                                                                                                                [ 58%]
will/tests/test_acl.py::test_verify_acl_is_allowed[eve, {'engineering_devs'}] PASSED                                                                                                                 [ 61%]
will/tests/test_acl.py::test_verify_acl_is_allowed[bob, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                              [ 64%]
will/tests/test_acl.py::test_verify_acl_is_allowed[Alice, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                            [ 67%]
will/tests/test_acl.py::test_verify_acl_is_allowed[eve, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                              [ 70%]
will/tests/test_acl.py::test_verify_acl_is_not_allowed[bob, {'engineering_devs'}] PASSED                                                                                                             [ 73%]
will/tests/test_acl.py::test_verify_acl_is_not_allowed[Alice, {'engineering_devs'}] PASSED                                                                                                           [ 76%]
will/tests/test_acl.py::test_verify_acl_is_not_allowed[eve, {'ENGINEERING_OPS'}] PASSED                                                                                                              [ 79%]
will/tests/test_acl.py::test_verify_acl_is_not_allowed[juan, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                         [ 82%]
will/tests/test_acl.py::test_verify_acl_is_not_allowed[pedro, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                        [ 85%]
will/tests/test_acl.py::test_verify_acl_no_backend_support[bob, {'engineering_devs'}] PASSED                                                                                                         [ 88%]
will/tests/test_acl.py::test_verify_acl_no_backend_support[Alice, {'engineering_devs'}] PASSED                                                                                                       [ 91%]
will/tests/test_acl.py::test_verify_acl_no_backend_support[eve, {'ENGINEERING_OPS'}] PASSED                                                                                                          [ 94%]
will/tests/test_acl.py::test_verify_acl_no_backend_support[juan, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                     [ 97%]
will/tests/test_acl.py::test_verify_acl_no_backend_support[pedro, {'engineering_devs', 'ENGINEERING_OPS'}] PASSED                                                                                    [100%]
```

### CODE REVIEW

**Comment by rsalmond** [comment]
Don't want to cut other folks who are interested in these testing improvements out of a little side discussion I started. I tried to dogpile onto @chillipeper's work over on [his fork](https://github.com/chillipeper/will/pull/1). TBH I dunno what the generally preferred approach is for collaborating across forks so if anyone has suggestions I'm game. Sorry if this is confusing!

**Comment by chillipeper** [comment]
cool, are we good to merge?  @Ashex @wontonst any objections?

cc: @brandonsturgeon

**Comment by Ashex** [comment]
This looks good to me!

**Comment by pastorhudson** [comment]
Progress! 🎉

**Comment by rsalmond** [comment]
```
$ grep test_acl * -r | wc
      0       0       0
```

LGTM, merging!

**Pull request merged**
