### PR TITLE
Fix image plugin

### PR DESCRIPTION
**Pull request by antgel**
It was good to see an updated image plugin, but I don't see how it can have worked. Fixed getattr syntax and checked for the correct array in the JSON response.

### CODE REVIEW

**Comment by antgel** [comment]
@skoczen Hi, I know things have been quiet until recently, do I need to create a separate issue for this PR?

**Comment by antgel** [comment]
I renamed the parameter as it was confusing, Google's terminology is quite specific, it's an "ID" not a "key".

**Comment by skoczen** [comment]
@antgel thanks for this PR, and glad to have you contributing!  No need to create a separate issue, it's all great to have here.

I suspect this comes from the API changes from google over the years since this plugin was first written to now - really glad to have it up to date.  

A couple of tweaks:

1. Would you mind updating the documentation for `image me` as well, and providing a link/instructions for people to generate their `GOOGLE_CUSTOM_SEARCH_ENGINE_ID`?
2. Can you add yourself to `AUTHORS` with the attribution you'd like?
3. I'm out of the loop on this, but if what `CUSTOM_SEARCH_KEY` used to be is the same as `ENGINE_ID`, it'd be great to provide backwards compatibility for existing installs. Do you have visibility into that?

Thanks for making will even better!

**Comment by antgel** [comment]
Hi, I've done (1) and (2). I don't see much point in (3) because the feature hasn't been working since the release, so the number of people using it was probably near-zero, and anybody without the keys gets a clueful error message.

**Comment by antgel** [comment]
Hi, I've done (1) and (2). I don't see much point in (3) because the feature hasn't been working since the release, so the number of people using it was probably near-zero, and anybody without the keys gets a clueful error message.

**Comment by antgel** [comment]
@skoczen Any updates on this going in?

**Comment by skoczen** [comment]
@antgel thanks for the ping - I thought I'd already merged it in! 

This will go in today or tomorrow, and out with an interim release as the [slack support](https://github.com/skoczen/will/pull/258), etc is finished up.  Thanks for the submission, and making will even better!

**Comment by skoczen** [comment]
Hey @antgel , just merged this in and released it as 0.9.5.  Just wanted to say thanks - especially for the *fantastically* well done docs!   So glad to have you aboard, making Will better!

**Pull request merged**
