### PR TITLE
Improve Slack Connection handling

### PR DESCRIPTION
**Pull request by Ashex**
This PR covers a couple things:

* The most recent releases of the slackapi library include an auto reconnect flag which has been added in.
* RTM disconnects either throw `WebSocketConnectionClosedException` or `SlackConnectionError`. I've added the second missing exception to the handling as presently will just loses its connection and never tries to reconnect. I've also tweak the import for websockets so that only the exception is imported.
* Raise version requirement of slackapi to current release.

### CODE REVIEW

**Comment by skoczen** [comment]
Hey @Ashex , welcome, and thanks much for the excellent contributions - and your patience with my slow replies!

This looks great, and I'll be merging this and your other PRs in shortly.  Would you mind adding yourself to `AUTHORS` in one of your PRs, with the attribution that you prefer?

**Comment by Ashex** [comment]
Not a problem! I'll update the pr with the contributor details soon, I'm on holiday at the moment but should be able to make time for this :-)

**Comment by Ashex** [comment]
Done :)

**Comment by BrianGallew** [comment]
+1 to getting this merged.

**Comment by skoczen** [comment]
This has been released in [2.1.3](http://skoczen.github.io/will/releases/#releases) - many thanks to @Ashex for the fix!   (pinging @BrianGallew as well, since it seems urgent for you!)

**Comment by BrianGallew** [comment]
Heh, I've already deployed 2.1.3.

**Pull request merged**
