### PR TITLE
Allow setting of plugin list from WILL_PLUGINS environment variable

### PR DESCRIPTION
**Pull request by mark-adams**
Similar to WILL_ROOMS, this lets you set the list of plugins using the WILL_PLUGINS environment variable.

### CODE REVIEW

**Comment by mark-adams** [comment]
This project is dead. Closing the PR.

**Comment by skoczen** [comment]
Reopening, same comment as others.

**Comment by skoczen** [comment]
I'm a +1 to this, but we'll need to update the documentation to indicate the `;` separator before releasing.  Holding off on merge for the moment, until I get that in!

**Comment by skoczen** [comment]
Merging this in to 1.0 - thanks for your submission!

**Pull request merged**
