### PR TITLE
allow to specify a custom config file location

### PR DESCRIPTION
**Pull request by yedpodtrzitko**
Hi,
using a hardcoded location of `config.py` is not always a suitable solution. I havent found any implemented mechanism how to specify a custom path for it, so here's a rough patch which allows it.  It would deserve some improvement, so before doing that I'd like to know what you think about this feature. Thanks.

### CODE REVIEW

**Comment by skoczen** [comment]
Hey @yedpodtrzitko ,

Thanks for the PR - I'm sort of a -0.5 to this, since it breaks pattern and I don't understand where it's needed. 

Can you elaborate a bit on your setup where using config.py isn't an acceptable solution?

**Comment by yedpodtrzitko** [comment]
I am not sure what kind of pattern breaking you have on your mind...
Anyway - the idea is simple. I cant/dont want to use environment variables. So I have a config file with credentials, but I dont want to commit it in the repo with the rest of the code. So the config lives somewhere else, but then there's no way how to say "look the config is elsewhere".


Also I've noticed the settings are initialized twice - first time it's because of the `import settings` clause ( https://github.com/skoczen/will/blob/master/will/main.py#L22 ), and the second time when `bootstrap()` is called ( https://github.com/skoczen/will/blob/master/will/main.py#L101 ). Is that on purpose?

**Comment by skoczen** [comment]
Hey @yedpodtrzitko 

Thanks for the info on your setup.  Keeping sensitive data in the environment is the pattern employed by will, (and broadly, meets [12-factor app](http://12factor.net/)).  The push for this pattern is intentional - it makes explicit where sensitive data is stored, and discourages it from living in checked in code.

In nearly all hosting environments, environmental variables are available, and thus make a good choice for sensitive data.

The pattern, more explicitly, is non-sensitive config lives with the codebase, sensitive config lives in env variables.  That one I'm a -1 to breaking.

I can be convinced that adding the "choose a different location for the config" feature is a good one, but it has to justify the additional complexity and confusion for novice users.  Right now, there's one "right" place to put things, and I'm in favor of keeping it that way.   But again, I'm listening.

Are you able to go into more detail about your setup?  Is it that you can't use env variables, or don't want to?

As for settings - they're actually run every time the module is imported.  It's meant to be idempotent, so no harm with it.

**Comment by skoczen** [comment]
I'm doing a big review, and closing this up, since it's been a month. If this is still an issue for you, please reopen!

**Pull request closed without merging**
