### PR TITLE
Python 3 support plus a bunch of other cleanup

### LINKED ISSUE #149: Upgrade requirements, python 3 compatibility.
It's time.  See #148.

### PR DESCRIPTION
**Pull request by Tenzer**
This should fix #149 and works in both Python 2 and 3 as far as I've been able to test.

When reviewing this code it will likely be easiest to take each commit by itself as I have grouped them by the changes they are making.

The Pylint changes came as I was looking through the code and saw things here and there that could be optimised. Let me know if there's some of those changes you disagree with.

### CODE REVIEW

**Comment by skoczen** [comment]
@Tenzer wow, this is a big one! 

Thanks so much for submitting it.   Will is currently in the middle of a huge upgrade (see #258 ), so the merge conflicts scare me a bit!  I won't merge this in until that's done, most likely, just to save work.

Overall, the fixes look pretty straightforward from the diff, and look great.  The one I'd push back on is pulling the unused imports from the plugins - they're there specifically so people can copy/paste, and see what's available without having to dig through the docs.  Would love to see those back!

Thanks again for bringing will into the py3k world!

**Comment by Tenzer** [comment]
I have added back the imports on the plugins, let me know if there's anything else I can do to make this merge-able.

**Comment by hobson** [comment]
Might this py3 update be merged before you complete #258 refactor so they can inform how you finish up #258 ?

**Comment by skoczen** [comment]
@hobson it might, but I'd rather tackle it separately, and finish out #258 as quickly as possible. 

I want py3 support, but I want to do it properly, and not hold up releases for it.  I know for a fact that there's stuff in the new encrypted messages that means fighting with py3's byte-string *decision*, and I'd rather keep my hair in while the refactor is happening. :) 

(Full disclosure: I've regretting moving to py3 on every large codebase I've moved to it, so this is making me drag my feet on this one a bit.  Thanks for your patience. )

**Comment by skoczen** [comment]
@Tenzer @hobson I actually decided that you both were right, and to just merge it now, release it as 1.0.1, and let folks test/use/give feedback on it.

@Tenzer thanks for all the work in getting this done!!

**Pull request merged**
