### PR TITLE
Feature: List all participants in the current room

### PR DESCRIPTION
**Pull request by puug**
Supports multi-page iteration

### CODE REVIEW

**Comment by skoczen** [comment]
Hey @puug , thanks for the PR, looks great!

I'm not crazy about the word "participants", but am totally good with it, since it's consistent with hipchat.

Two things that would be great if you've got time to toss them on:

1. Some quick docs.
2. Please add yourself to the `AUTHORS` file, with the attribution you'd like.

Thanks for making will better!

**Comment by puug** [comment]
@skoczen no worries. Added a quick entry for the new command.

**Comment by skoczen** [comment]
Merging in, will ping here when it's released - should be today!

**Comment by skoczen** [comment]
This is released (with a bunch of other stuff) as v[0.8](http://skoczen.github.io/will/improve/#releases)!

**Pull request merged**
