### PR TITLE
Updated the MkDocs config from the deprecated format

### PR DESCRIPTION
**Pull request by d0ugal**

### CODE REVIEW

**Comment by skoczen** [comment]
Awesome.  Thanks for this - will it merged in and released on my next sprint!

Would you mind adding yourself to the AUTHORS file?

Thanks!
-Steven

**Comment by d0ugal** [comment]
Done

**Comment by skoczen** [comment]
Fantastic.  Thanks!

**Comment by skoczen** [comment]
Hey, just tossing out a quick note on this and all the other PRs to say thanks for your patience.  

Neither will nor your contributions have been forgotten!

We've just launched our app at my day job, and given that I'm currently the entirely of the dev team, finding cycles for open-source work hasn't been possible.  Things are settling down though, and I should have a proper block of time at the end of next sprint (end of September.)  Thanks for hanging in there!

**Comment by d0ugal** [comment]
No problem :)

**Comment by d0ugal** [comment]
Looks like the merge conflict resolution didn't work - I see merge markers in the master.

**Comment by skoczen** [comment]
Yep, just merged about 15 branches in, definitely some cleanup to do! 

Thanks for the good eyes!

**Comment by skoczen** [comment]
This is released in [0.9.3](http://skoczen.github.io/will/improve/#releases) - thank you so much for your patience, and even more so for your contributions that made will even better!

-Steven

**Pull request merged**
